--[[
    GlowHub V4 - Advanced Script
    Generated by Gemini
]]

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")
local UserInputService = game:GetService("UserInputService")
local TweenService = game:GetService("TweenService")
local StarterGui = game:GetService("StarterGui")

local LocalPlayer = Players.LocalPlayer
local Camera = workspace.CurrentCamera
local Mouse = LocalPlayer:GetMouse()

-- // Settings //
local UI_COLOR = Color3.fromRGB(20, 20, 20)
local ACCENT_COLOR = Color3.fromRGB(0, 120, 215)
local TEXT_COLOR = Color3.fromRGB(255, 255, 255)

-- // Variables for Features //
local toggles = {}
local savedCFrame = nil
local flyActive = false
local noclipActive = false
local infJumpActive = false
local walkFlingActive = false
local flySpeed = 50

-- // UI CREATION //
local ScreenGui = Instance.new("ScreenGui")
ScreenGui.Name = "GlowHubV4"
ScreenGui.ResetOnSpawn = false
ScreenGui.Parent = game.CoreGui -- Or LocalPlayer.PlayerGui if using in Studio

-- Main Frame
local MainFrame = Instance.new("Frame")
MainFrame.Name = "MainPanel"
MainFrame.Size = UDim2.new(0, 240, 0, 400)
MainFrame.Position = UDim2.new(0.5, -120, 1.2, 0) -- Hidden at bottom initially
MainFrame.BackgroundColor3 = UI_COLOR
MainFrame.BorderSizePixel = 0
MainFrame.ClipsDescendants = true
MainFrame.Parent = ScreenGui

local UICorner = Instance.new("UICorner")
UICorner.CornerRadius = UDim.new(0, 12)
UICorner.Parent = MainFrame

-- Top Bar
local TopBar = Instance.new("Frame")
TopBar.Size = UDim2.new(1, 0, 0, 35)
TopBar.BackgroundColor3 = ACCENT_COLOR
TopBar.BorderSizePixel = 0
TopBar.Parent = MainFrame

local TopBarCorner = Instance.new("UICorner")
TopBarCorner.CornerRadius = UDim.new(0, 12)
TopBarCorner.Parent = TopBar

local Title = Instance.new("TextLabel")
Title.Text = "GlowHub V4"
Title.Size = UDim2.new(1, 0, 1, 0)
Title.BackgroundTransparency = 1
Title.TextColor3 = TEXT_COLOR
Title.Font = Enum.Font.GothamBold
Title.TextSize = 16
Title.Parent = TopBar

-- Hide bottom corners of TopBar to match MainFrame
local Cover = Instance.new("Frame")
Cover.Size = UDim2.new(1, 0, 0, 10)
Cover.Position = UDim2.new(0, 0, 1, -10)
Cover.BackgroundColor3 = ACCENT_COLOR
Cover.BorderSizePixel = 0
Cover.Parent = TopBar

-- Scrolling Frame
local ScrollFrame = Instance.new("ScrollingFrame")
ScrollFrame.Size = UDim2.new(1, -10, 1, -45)
ScrollFrame.Position = UDim2.new(0, 5, 0, 40)
ScrollFrame.BackgroundTransparency = 1
ScrollFrame.ScrollBarThickness = 4
ScrollFrame.CanvasSize = UDim2.new(0, 0, 2, 0) -- Adjusted automatically later
ScrollFrame.Parent = MainFrame

local UIListLayout = Instance.new("UIListLayout")
UIListLayout.Parent = ScrollFrame
UIListLayout.SortOrder = Enum.SortOrder.LayoutOrder
UIListLayout.Padding = UDim.new(0, 5)

-- Floating Button (G)
local FloatBtn = Instance.new("TextButton")
FloatBtn.Size = UDim2.new(0, 45, 0, 45)
FloatBtn.Position = UDim2.new(0.1, 0, 0.1, 0)
FloatBtn.BackgroundColor3 = ACCENT_COLOR
FloatBtn.Text = "G"
FloatBtn.TextColor3 = TEXT_COLOR
FloatBtn.Font = Enum.Font.GothamBold
FloatBtn.TextSize = 24
FloatBtn.Parent = ScreenGui

local FloatCorner = Instance.new("UICorner")
FloatCorner.CornerRadius = UDim.new(1, 0) -- Circle
FloatCorner.Parent = FloatBtn

-- // FUNCTIONS //

-- Draggable Function
local function makeDraggable(guiObj)
    local dragging, dragInput, dragStart, startPos
    guiObj.InputBegan:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseButton1 then
            dragging = true
            dragStart = input.Position
            startPos = guiObj.Position
            input.Changed:Connect(function()
                if input.UserInputState == Enum.UserInputState.End then dragging = false end
            end)
        end
    end)
    guiObj.InputChanged:Connect(function(input)
        if input.UserInputType == Enum.UserInputType.MouseMovement then
            dragInput = input
        end
    end)
    UserInputService.InputChanged:Connect(function(input)
        if input == dragInput and dragging then
            local delta = input.Position - dragStart
            guiObj.Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + delta.X, startPos.Y.Scale, startPos.Y.Offset + delta.Y)
        end
    end)
end

makeDraggable(MainFrame)
makeDraggable(FloatBtn)

-- Toggle UI Animation
local isOpen = false
local function toggleMenu()
    isOpen = not isOpen
    local targetPos = isOpen and UDim2.new(0.5, -120, 0.5, -200) or UDim2.new(0.5, -120, 1.2, 0)
    TweenService:Create(MainFrame, TweenInfo.new(0.5, Enum.EasingStyle.Back, Enum.EasingDirection.Out), {Position = targetPos}):Play()
end

FloatBtn.MouseButton1Click:Connect(toggleMenu)

-- Smart Close
UserInputService.InputBegan:Connect(function(input)
    if input.UserInputType == Enum.UserInputType.MouseButton1 and isOpen then
        local mousePos = UserInputService:GetMouseLocation()
        local framePos = MainFrame.AbsolutePosition
        local frameSize = MainFrame.AbsoluteSize
        -- Check if click is OUTSIDE frame and OUTSIDE float button
        if (mousePos.X < framePos.X or mousePos.X > framePos.X + frameSize.X or
           mousePos.Y < framePos.Y + 36 or mousePos.Y > framePos.Y + frameSize.Y + 36) then -- +36 offsets GUI inset
            -- Simplified check for float button overlap omitted for brevity
            toggleMenu()
        end
    end
end)

-- Function to create Toggles
local function createToggle(name, callback)
    local ToggleBtn = Instance.new("TextButton")
    ToggleBtn.Size = UDim2.new(1, 0, 0, 35)
    ToggleBtn.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
    ToggleBtn.Text = name
    ToggleBtn.TextColor3 = TEXT_COLOR
    ToggleBtn.Font = Enum.Font.GothamSemibold
    ToggleBtn.TextSize = 14
    ToggleBtn.Parent = ScrollFrame
    
    local ToggleCorner = Instance.new("UICorner")
    ToggleCorner.CornerRadius = UDim.new(0, 6)
    ToggleCorner.Parent = ToggleBtn
    
    local Status = Instance.new("Frame")
    Status.Size = UDim2.new(0, 10, 0, 10)
    Status.Position = UDim2.new(0.9, 0, 0.5, -5)
    Status.BackgroundColor3 = Color3.fromRGB(150, 150, 150) -- Gray (Off)
    Status.Parent = ToggleBtn
    
    local StatusCorner = Instance.new("UICorner")
    StatusCorner.CornerRadius = UDim.new(1, 0)
    StatusCorner.Parent = Status
    
    local enabled = false
    ToggleBtn.MouseButton1Click:Connect(function()
        enabled = not enabled
        Status.BackgroundColor3 = enabled and Color3.fromRGB(0, 255, 100) or Color3.fromRGB(150, 150, 150)
        callback(enabled)
    end)
end

-- Function for Value Changer (Speed/Jump)
local function createValueAdjuster(name, default, callback)
    local Frame = Instance.new("Frame")
    Frame.Size = UDim2.new(1, 0, 0, 40)
    Frame.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
    Frame.Parent = ScrollFrame
    local Corner = Instance.new("UICorner"); Corner.Parent = Frame
    
    local Label = Instance.new("TextLabel")
    Label.Text = name .. ": " .. default
    Label.Size = UDim2.new(0.5, 0, 1, 0)
    Label.BackgroundTransparency = 1
    Label.TextColor3 = TEXT_COLOR
    Label.Parent = Frame
    
    local Minus = Instance.new("TextButton")
    Minus.Text = "-"
    Minus.Size = UDim2.new(0, 30, 0, 30)
    Minus.Position = UDim2.new(0.6, 0, 0.5, -15)
    Minus.BackgroundColor3 = ACCENT_COLOR
    Minus.Parent = Frame
    
    local Plus = Instance.new("TextButton")
    Plus.Text = "+"
    Plus.Size = UDim2.new(0, 30, 0, 30)
    Plus.Position = UDim2.new(0.8, 0, 0.5, -15)
    Plus.BackgroundColor3 = ACCENT_COLOR
    Plus.Parent = Frame
    
    local value = default
    Minus.MouseButton1Click:Connect(function() value = value - 5; Label.Text = name..": "..value; callback(value) end)
    Plus.MouseButton1Click:Connect(function() value = value + 5; Label.Text = name..": "..value; callback(value) end)
end

-- // FEATURE IMPLEMENTATION //

-- 1. Movement
createValueAdjuster("Speed", 16, function(val)
    toggles.SpeedVal = val
end)
createToggle("Enable Speed Loop", function(state)
    toggles.SpeedLoop = state
end)

createValueAdjuster("Jump", 50, function(val)
    toggles.JumpVal = val
end)
createToggle("Enable Jump Loop", function(state)
    toggles.JumpLoop = state
end)

RunService.RenderStepped:Connect(function()
    if LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("Humanoid") then
        if toggles.SpeedLoop then LocalPlayer.Character.Humanoid.WalkSpeed = toggles.SpeedVal end
        if toggles.JumpLoop then LocalPlayer.Character.Humanoid.UseJumpPower = true; LocalPlayer.Character.Humanoid.JumpPower = toggles.JumpVal end
    end
end)

-- Infinite Jump
UserInputService.JumpRequest:Connect(function()
    if infJumpActive and LocalPlayer.Character then
        LocalPlayer.Character:FindFirstChildOfClass("Humanoid"):ChangeState("Jumping")
    end
end)
createToggle("Infinite Jump", function(state) infJumpActive = state end)

-- 2. Physics & Combat
-- Noclip
RunService.Stepped:Connect(function()
    if noclipActive and LocalPlayer.Character then
        for _, part in pairs(LocalPlayer.Character:GetDescendants()) do
            if part:IsA("BasePart") and part.CanCollide == true then
                part.CanCollide = false
            end
        end
    end
end)
createToggle("Noclip", function(state) noclipActive = state end)

-- WalkFling (Spin based)
createToggle("WalkFling (Spin)", function(state)
    walkFlingActive = state
    if not state and LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart") then
        LocalPlayer.Character.HumanoidRootPart.RotVelocity = Vector3.new(0,0,0)
    end
end)

RunService.Heartbeat:Connect(function()
    if walkFlingActive and LocalPlayer.Character and LocalPlayer.Character:FindFirstChild("HumanoidRootPart") then
        local root = LocalPlayer.Character.HumanoidRootPart
        root.RotVelocity = Vector3.new(0, 10000, 0) -- High Rotation to fling on touch
        root.Velocity = Vector3.new(root.Velocity.X, 0, root.Velocity.Z) -- Keep stable vertically
    end
end)

-- Stable Fly
createToggle("Stable Fly", function(state)
    flyActive = state
    local root = LocalPlayer.Character:WaitForChild("HumanoidRootPart")
    local bodyGyro, bodyVel
    
    if state then
        -- Setup Fly physics
        bodyGyro = Instance.new("BodyGyro", root)
        bodyGyro.P = 9e4
        bodyGyro.maxTorque = Vector3.new(9e9, 9e9, 9e9)
        bodyGyro.CFrame = root.CFrame
        
        bodyVel = Instance.new("BodyVelocity", root)
        bodyVel.velocity = Vector3.new(0, 0.1, 0)
        bodyVel.maxForce = Vector3.new(9e9, 9e9, 9e9)
        
        -- Fly Loop
        task.spawn(function()
            while flyActive and LocalPlayer.Character do
                RunService.RenderStepped:Wait()
                if not root then break end
                
                bodyGyro.CFrame = Camera.CFrame
                local moveDir = Vector3.new()
                
                if UserInputService:IsKeyDown(Enum.KeyCode.W) then moveDir = moveDir + Camera.CFrame.LookVector end
                if UserInputService:IsKeyDown(Enum.KeyCode.S) then moveDir = moveDir - Camera.CFrame.LookVector end
                if UserInputService:IsKeyDown(Enum.KeyCode.D) then moveDir = moveDir + Camera.CFrame.RightVector end
                if UserInputService:IsKeyDown(Enum.KeyCode.A) then moveDir = moveDir - Camera.CFrame.RightVector end
                
                bodyVel.Velocity = moveDir * flySpeed
            end
            if bodyGyro then bodyGyro:Destroy() end
            if bodyVel then bodyVel:Destroy() end
        end)
    else
        -- Cleanup
        for _, v in pairs(root:GetChildren()) do
            if v:IsA("BodyGyro") or v:IsA("BodyVelocity") then v:Destroy() end
        end
    end
end)

-- 3. Advanced Skills
-- Auto-Back
local function onCharacterAdded(char)
    if savedCFrame then
        task.delay(4, function()
            if char:FindFirstChild("HumanoidRootPart") then
                char.HumanoidRootPart.CFrame = savedCFrame
                savedCFrame = nil -- Reset after use
            end
        end)
    end
    char:WaitForChild("Humanoid").Died:Connect(function()
        if toggles.AutoBack and char:FindFirstChild("HumanoidRootPart") then
            savedCFrame = char.HumanoidRootPart.CFrame
        end
    end)
end
LocalPlayer.CharacterAdded:Connect(onCharacterAdded)
if LocalPlayer.Character then onCharacterAdded(LocalPlayer.Character) end

createToggle("Auto-Back (Survival)", function(state)
    toggles.AutoBack = state
end)

-- Fast Tools (Remove Cooldown attempt)
createToggle("Fast Tools", function(state)
    toggles.FastTools = state
    -- Note: Truly removing cooldown depends on the tool script, this is a generic attempt
    if state then
         Mouse.Button1Down:Connect(function()
            if toggles.FastTools and LocalPlayer.Character then
                local tool = LocalPlayer.Character:FindFirstChildOfClass("Tool")
                if tool then
                    tool:Activate()
                end
            end
        end)
    end
end)

-- 4. Player System
local selectedPlayer = nil
local PlayerDropdown = Instance.new("TextButton")
PlayerDropdown.Size = UDim2.new(1, 0, 0, 35)
PlayerDropdown.BackgroundColor3 = Color3.fromRGB(30, 30, 30)
PlayerDropdown.Text = "Select Player: None"
PlayerDropdown.TextColor3 = TEXT_COLOR
PlayerDropdown.Parent = ScrollFrame
local DropCorner = Instance.new("UICorner"); DropCorner.Parent = PlayerDropdown

local DropList = Instance.new("ScrollingFrame")
DropList.Size = UDim2.new(1, 0, 0, 100)
DropList.Position = UDim2.new(0, 0, 1, 5)
DropList.Visible = false
DropList.Parent = PlayerDropdown
DropList.CanvasSize = UDim2.new(0,0,0,0) -- Dynamic

local ListLayout = Instance.new("UIListLayout")
ListLayout.Parent = DropList

local function updatePlayerList()
    for _, child in pairs(DropList:GetChildren()) do
        if child:IsA("TextButton") then child:Destroy() end
    end
    
    for _, plr in pairs(Players:GetPlayers()) do
        if plr ~= LocalPlayer then
            local btn = Instance.new("TextButton")
            btn.Size = UDim2.new(1, 0, 0, 25)
            btn.Text = plr.Name
            btn.BackgroundColor3 = Color3.fromRGB(50, 50, 50)
            btn.TextColor3 = TEXT_COLOR
            btn.Parent = DropList
            btn.MouseButton1Click:Connect(function()
                selectedPlayer = plr
                PlayerDropdown.Text = "Selected: " .. plr.Name
                DropList.Visible = false
            end)
        end
    end
    DropList.CanvasSize = UDim2.new(0, 0, 0, #DropList:GetChildren() * 25)
end

PlayerDropdown.MouseButton1Click:Connect(function()
    DropList.Visible = not DropList.Visible
    updatePlayerList()
end)

-- Teleport Button
local TPBtn = Instance.new("TextButton")
TPBtn.Size = UDim2.new(1, 0, 0, 35)
TPBtn.BackgroundColor3 = ACCENT_COLOR
TPBtn.Text = "Teleport to Player"
TPBtn.TextColor3 = TEXT_COLOR
TPBtn.Parent = ScrollFrame
local TPCorner = Instance.new("UICorner"); TPCorner.Parent = TPBtn

TPBtn.MouseButton1Click:Connect(function()
    if selectedPlayer and selectedPlayer.Character and selectedPlayer.Character:FindFirstChild("HumanoidRootPart") and LocalPlayer.Character then
        LocalPlayer.Character.HumanoidRootPart.CFrame = selectedPlayer.Character.HumanoidRootPart.CFrame * CFrame.new(0, 0, 3)
    end
end)

-- Skin Copy (Client Side)
local SkinBtn = Instance.new("TextButton")
SkinBtn.Size = UDim2.new(1, 0, 0, 35)
SkinBtn.BackgroundColor3 = Color3.fromRGB(100, 50, 200)
SkinBtn.Text = "Copy Skin (Client)"
SkinBtn.TextColor3 = TEXT_COLOR
SkinBtn.Parent = ScrollFrame
local SkinCorner = Instance.new("UICorner"); SkinCorner.Parent = SkinBtn

SkinBtn.MouseButton1Click:Connect(function()
    if selectedPlayer and LocalPlayer.Character then
        local hum = LocalPlayer.Character:FindFirstChild("Humanoid")
        if hum then
            -- Attempt to apply HumanoidDescription
            pcall(function()
                local desc = Players:GetHumanoidDescriptionFromUserId(selectedPlayer.UserId)
                hum:ApplyDescription(desc)
            end)
        end
    end
end)

-- Resize Canvas
UIListLayout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
    ScrollFrame.CanvasSize = UDim2.new(0, 0, 0, UIListLayout.AbsoluteContentSize.Y + 10)
end)

print("GlowHub V4 Loaded Successfully")
